version: "3.9"

services:
  server:
    build: ./server
    container_name: mafia-server
    ports:
      - "3001:3001"
    restart: always
    networks:
      - mafia-net

  client:
    build: ./client
    container_name: mafia-client
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - server
    networks:
      - mafia-net

networks:
  mafia-net:
    driver: bridge
